
version: '3.1'

services:

  db:
    image: postgres
    # restart: always
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: d1r3c7us
      POSTGRES_USER: admin
      POSTGRES_DB: directus

